version: '3.8'

services:
  vue-app:
    image: ${IMAGE_NAME}:latest
    container_name: frontend-sispa
    ports:
      - "8081:80"

    environment:
      - NODE_ENV=production
      - VITE_API_LOCAL_URL=${BACKEND_URL}
    restart: always
