name: Hostinger CI/CD Pipeline

on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  workflows: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install dependencies and build Vue project
        run: |
          echo "Install dependencies and build Vue project"
          node -v
          npm -v
          npm install
          npm run build

      - name: List contents of dist directory
        run: |
          ls -la

      - name: Archive production build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist

      - name: List downloaded files
        run: |
          ls -la

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          echo "Build Docker image..."
          docker build --build-arg VITE_API_LOCAL_URL=${{ secrets.BACKEND_URL }} -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} -f Dockerfile .

      - name: Push image to registry
        run: |
          echo "Push image to registry..."
          docker push ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DEPLOY_SERVER }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set permissions for known_hosts

      - name: Deploy to Hostinger VPS
        run: |
          ssh "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}" "mkdir -p ~/frontend/"
          rsync -rahv docker-compose-deploy.yml "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}:~/frontend/"
          ssh "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}" "
            export IMAGE_NAME=${{ secrets.IMAGE_NAME }} &&
            export BACKEND_URL=${{ secrets.BACKEND_URL }} &&
            docker rm -f frontend-vue-app-1 || true &&
            cd ~/frontend &&
            docker compose -f docker-compose-deploy.yml up -d --pull always
          "

  clean:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DEPLOY_SERVER }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts  # Set permissions for known_hosts

      - name: Clean up old Docker images
        run: |
          ssh "${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }}" "docker system prune -f"